### ISSUE TITLE
Bonusaufgabe

### ISSUE THREAD

**Issue by Telerick** [Telerick/VS-Praktikum#15]
Wenn Sie den Bonus erwerben wollen, überlegen Sie auch, ob die 
hier beschriebene Kommunikation wirklich ausreicht. Wie sollen die Börsen wissen, an wen Sie Nachrichten schicken sollen? Weiter, während manche Wertpapiere mehrmals per Sekunde gehandelt werden, werden andere ein oder zweimal per Jahr gehandelt. Wie soll eine Bank wissen, wie viel ein solches Wertpapierwert ist?

**Comment by LangenT** [comment]
**Wie soll Bank wissen was ein lange nicht gehandeltes Papier Wert ist?**

- Der Wert einer Aktie ist ein zusammentreffen des Angebots und der Nachfrage. Angebot und Nachfrage werden in einem Orderbuch geführt, welches stetig aktualisiert und frei einsehbar ist. Kommt es zu einer Übereinstimmung eines limits des Käufers und Verkäufers, kommt es zu einer Transaktion. Der Wert einer Aktie wird nach jeder Transaktion am Handelsplatz aktualisiert und entspricht dem Kurs der letzten Transaktion. Sollte ein Wertpapier lange nicht gehandelt worden sein, so hat sich der Kurs einer Aktie auch nicht verändert. Verkaufsangebote oder Kaufangebote zu einem bestimmten Preis können immer gestellt werden, ob sie zu einer Transaktion führen (angenommen werden) ist die andere Sache.
